### ISSUE TITLE
Multiple alicats on single serial port cause access problems

### ISSUE THREAD

**Issue by alexrudd2** [alexrudd2/alicat#30]
> Hello,
> 
> I am trying to use the latests version (0.7.0) but when I try using my breakout box with multiple alicats. Example: `self.mfcs = { "A": FlowController(address=com_port, unit='A'), "B": FlowController(address=com_port, unit='B'), "C": FlowController(address=com_port,unit='C'), }`
> 
> I get an error : could not open port 'COM3': PermissionError(13, 'Access is denied.', None, 5)
> 
> When I go back to version 0.4.0 it works just fine, after making the proper adjustments for the arguments.
> 
> If I do it with just one MFC it works, any ideas on what I might be doing wrong?

Originally posted by @picarro-jmoreno in https://github.com/numat/alicat/issues/144#issue-2677184702

**Comment by alexrudd2** [comment]
Per our email correspondence, `0.4.0` works but `0.7.0` does not.  The culprit appears to be this [removed code](https://github.com/numat/alicat/pull/37/files#diff-ea36efb8c0fa7d6dadf8ee534d3cbab0f33b1317b1c3ebf313cc1f68986c0518L35-L40) which re-used serial connections.

```python
if port in FlowMeter.open_ports:
    self.connection, refcount = FlowMeter.open_ports[port]
    FlowMeter.open_ports[port] = (self.connection, refcount + 1)
else:
    self.connection = serial.Serial(port, 19200, timeout=1.0)
    FlowMeter.open_ports[port] = (self.connection, 1)
```

@picarro-moreno had success changing 0.7.0 to look like below
![unnamed](https://github.com/user-attachments/assets/f29abfd2-8eaa-4fce-8919-9f831b888a8a)

**Comment by alexrudd2** [comment]
@patr1ck Are you also affected by this?  (Do you use multiple alicats on the same port?)

**Comment by patr1ck** [comment]
Hello! Sorry for the late comment. We do use multiple Alicats on the same port, but I haven't seen this, maybe due to the way we create the FlowController connections (on different threads).

**Comment by alexrudd2** [comment]
> Hello! Sorry for the late comment. We do use multiple Alicats on the same port, but I haven't seen this, maybe due to the way we create the FlowController connections (on different threads).

Ok, great.  You should be unaffected by `0.8.0`, but please let me know if I've broken something. :)
